services:
    frontend:
        build: frontend
        ports:
            - "3000:3000"

    backend:
        build: backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend/data.json:/app/data.json
        extra_hosts:
            - "host.docker.internal:host-gateway"

    
